# Generated by Django 5.0.7 on 2024-09-10 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JubanClientInventoryFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JubanInventorySupplierFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JubanItemCodeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100)),
                ('po_product_name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JubanSiteInventoryFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JubanSupplierFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JubanItemInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Date')),
                ('item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('po_product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('new_product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity_in', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity_out', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('site_or_client_choice', models.CharField(blank=True, choices=[('site', 'Site Delivered'), ('client', 'Client')], max_length=10, null=True)),
                ('site_delivered', models.CharField(blank=True, max_length=255, null=True, verbose_name='Site Delivered')),
                ('client', models.CharField(blank=True, max_length=255, null=True, verbose_name='Client')),
                ('delivery_ref', models.CharField(blank=True, choices=[('PL', 'PL'), ('DR', 'DR'), ('TR', 'TR')], max_length=2, null=True, verbose_name='Delivery Ref#')),
                ('delivery_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Delivery No.')),
                ('invoice_type', models.CharField(blank=True, choices=[('SI', 'SI'), ('TR', 'TR'), ('CI', 'CI')], max_length=10, null=True, verbose_name='Invoice#')),
                ('invoice_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Invoice No.')),
                ('client_inventory_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='JubanShop.jubanclientinventoryfolder')),
                ('site_inventory_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='JubanShop.jubansiteinventoryfolder')),
            ],
        ),
        migrations.CreateModel(
            name='JubanCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JubanShop.jubaniteminventory')),
            ],
        ),
        migrations.CreateModel(
            name='JubanInventoryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('po_product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('new_product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity_in', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity_out', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('site_delivered', models.CharField(blank=True, max_length=255, null=True, verbose_name='Site Delivered')),
                ('client', models.CharField(blank=True, max_length=255, null=True, verbose_name='Client')),
                ('delivery_ref', models.CharField(choices=[('PL', 'PL'), ('DR', 'DR'), ('TR', 'TR')], max_length=2, null=True, verbose_name='Delivery Ref#')),
                ('delivery_no', models.CharField(max_length=255, null=True, verbose_name='Delivery No.')),
                ('invoice_type', models.CharField(blank=True, choices=[('SI', 'SI'), ('Invoice', 'Invoice'), ('CI', 'CI')], max_length=10, null=True, verbose_name='Invoice#')),
                ('invoice_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Invoice No.')),
                ('site_or_client_choice', models.CharField(blank=True, choices=[('site', 'Site Delivered'), ('client', 'Client')], max_length=10, null=True)),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('client_inventory_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='JubanShop.jubanclientinventoryfolder')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JubanShop.jubaniteminventory')),
                ('site_inventory_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='JubanShop.jubansiteinventoryfolder')),
            ],
        ),
        migrations.CreateModel(
            name='JubanStockInHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('po_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='PO#')),
                ('purchaser', models.CharField(blank=True, max_length=255, null=True, verbose_name='Purchaser')),
                ('item_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Item Code')),
                ('particulars', models.CharField(blank=True, max_length=255, null=True, verbose_name='Particulars')),
                ('quantity_in', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=255, null=True, verbose_name='Unit')),
                ('fbbd_ref_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='FBBD Ref#')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('supplier', models.CharField(blank=True, max_length=255, null=True, verbose_name='Supplier')),
                ('delivery_ref', models.CharField(blank=True, choices=[('PL', 'PL'), ('DR', 'DR'), ('TR', 'TR')], max_length=2, null=True, verbose_name='Delivery Ref#')),
                ('delivery_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Delivery No.')),
                ('invoice_type', models.CharField(blank=True, choices=[('SI', 'SI'), ('Invoice', 'Invoice'), ('CI', 'CI')], max_length=10, null=True, verbose_name='Invoice#')),
                ('invoice_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Invoice No.')),
                ('payment_req_ref', models.CharField(blank=True, max_length=255, null=True, verbose_name='Payment Req Ref#')),
                ('payment_details', models.TextField(blank=True, choices=[('Check Voucher', 'Check Voucher'), ('Cash Voucher', 'Cash Voucher')], max_length=20, null=True, verbose_name='Payment Details')),
                ('remarks2', models.CharField(blank=True, choices=[('On Hold', 'On Hold'), ('For Signature', 'For Signature'), ('Cancelled', 'Cancelled'), ('Paid', 'Paid')], max_length=20, null=True, verbose_name='Remarks2')),
                ('supplier_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='JubanShop.jubaninventorysupplierfolder')),
            ],
        ),
    ]
