# Generated by Django 5.0.7 on 2024-08-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Date')),
                ('po_number', models.CharField(max_length=255, verbose_name='PO#')),
                ('purchaser', models.CharField(max_length=255, verbose_name='Purchaser')),
                ('brand', models.CharField(max_length=255, verbose_name='Brand')),
                ('item_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Item Code')),
                ('particulars', models.CharField(max_length=255, verbose_name='Particulars')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('unit', models.CharField(max_length=255, verbose_name='Unit')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount')),
                ('site_delivered', models.CharField(max_length=255, verbose_name='Site Delivered')),
                ('fbbd_ref_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='FBBD Ref#')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('supplier', models.CharField(max_length=255, verbose_name='Supplier')),
                ('delivery_ref', models.CharField(choices=[('PL', 'PL'), ('DR', 'DR'), ('TR', 'TR')], max_length=2, verbose_name='Delivery Ref#')),
                ('delivery_no', models.CharField(max_length=255, verbose_name='Delivery No.')),
                ('invoice_type', models.CharField(choices=[('SI', 'SI'), ('Invoice', 'Invoice'), ('CI', 'CI')], max_length=10, verbose_name='Invoice#')),
                ('invoice_no', models.CharField(max_length=255, verbose_name='Invoice No.')),
                ('payment_req_ref', models.CharField(max_length=255, verbose_name='Payment Req Ref#')),
                ('payment_details', models.TextField(blank=True, null=True, verbose_name='Payment Details')),
                ('remarks2', models.CharField(choices=[('On Hold', 'On Hold'), ('For Signature', 'For Signature'), ('Cancelled', 'Cancelled'), ('Paid', 'Paid')], max_length=20, verbose_name='Remarks2')),
            ],
        ),
    ]
