# Generated by Django 5.0.7 on 2024-08-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='brand',
            field=models.CharField(max_length=255, null=True, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_no',
            field=models.CharField(max_length=255, null=True, verbose_name='Delivery No.'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_ref',
            field=models.CharField(choices=[('PL', 'PL'), ('DR', 'DR'), ('TR', 'TR')], max_length=2, null=True, verbose_name='Delivery Ref#'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='invoice_no',
            field=models.CharField(max_length=255, null=True, verbose_name='Invoice No.'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='invoice_type',
            field=models.CharField(choices=[('SI', 'SI'), ('Invoice', 'Invoice'), ('CI', 'CI')], max_length=10, null=True, verbose_name='Invoice#'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='payment_req_ref',
            field=models.CharField(max_length=255, null=True, verbose_name='Payment Req Ref#'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='remarks2',
            field=models.CharField(choices=[('On Hold', 'On Hold'), ('For Signature', 'For Signature'), ('Cancelled', 'Cancelled'), ('Paid', 'Paid')], max_length=20, null=True, verbose_name='Remarks2'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='site_delivered',
            field=models.CharField(max_length=255, null=True, verbose_name='Site Delivered'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.CharField(max_length=255, null=True, verbose_name='Supplier'),
        ),
    ]
