# Generated by Django 5.0.7 on 2024-08-09 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0002_alter_purchaseorder_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Invoice No.'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='invoice_type',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('Invoice', 'Invoice'), ('CI', 'CI')], max_length=10, null=True, verbose_name='Invoice#'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='payment_req_ref',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Payment Req Ref#'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='site_delivered',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Site Delivered'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Unit'),
        ),
    ]
