# Generated by Django 5.0.7 on 2024-08-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0004_archivefolder_purchaseorder_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(max_length=255, null=True, verbose_name='PO#'),
        ),
    ]
