# Generated by Django 5.0.7 on 2024-08-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0005_alter_purchaseorder_po_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='date',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='particulars',
            field=models.CharField(max_length=255, null=True, verbose_name='Particulars'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchaser',
            field=models.CharField(max_length=255, null=True, verbose_name='Purchaser'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Total Amount'),
        ),
    ]
