# Generated by Django 4.2.1 on 2024-08-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0006_alter_purchaseorder_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier', models.CharField(max_length=100)),
                ('po_product_name', models.CharField(max_length=100)),
                ('new_product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(max_length=50)),
                ('quantity_in', models.PositiveIntegerField()),
                ('quantity_out', models.PositiveIntegerField(default=0)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
    ]
