# Generated by Django 4.2.1 on 2024-08-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0007_iteminventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminventory',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
