# Generated by Django 4.2.1 on 2024-08-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0009_alter_iteminventory_po_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminventory',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
