# Generated by Django 4.2.1 on 2024-08-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0011_alter_iteminventory_quantity_in_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
