# Generated by Django 4.2.1 on 2024-08-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0013_alter_purchaseorder_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Supplier'),
        ),
        migrations.DeleteModel(
            name='SupplierFolder',
        ),
    ]
