# Generated by Django 5.0.7 on 2024-08-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0014_alter_purchaseorder_supplier_delete_supplierfolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
