# Generated by Django 5.0.7 on 2024-08-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0015_purchaseorder_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='payment_details',
            field=models.TextField(blank=True, choices=[('Check Voucher', 'Check Voucher'), ('Cash Voucher', 'Cash Voucher')], max_length=20, null=True, verbose_name='Payment Details'),
        ),
    ]
