# Generated by Django 5.0.7 on 2024-08-19 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0017_supplierfolder_purchaseorder_supplier_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='supplier_folder',
        ),
        migrations.DeleteModel(
            name='SupplierFolder',
        ),
    ]
