# Generated by Django 5.0.7 on 2024-08-19 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0018_remove_purchaseorder_supplier_folder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='po.supplierfolder'),
        ),
    ]
