# Generated by Django 5.0.7 on 2024-08-20 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0019_supplierfolder_purchaseorder_supplier_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminventory',
            name='date',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='iteminventory',
            name='site_delivered',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Site Delivered'),
        ),
    ]
