# Generated by Django 5.0.7 on 2024-08-20 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0020_iteminventory_date_iteminventory_site_delivered'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('po_product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('new_product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity_in', models.IntegerField()),
                ('quantity_out', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('site_delivered', models.CharField(blank=True, max_length=255, null=True, verbose_name='Site Delivered')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='po.iteminventory')),
            ],
        ),
    ]
