# Generated by Django 5.0.7 on 2024-08-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0021_inventoryhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInventoryFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
