# Generated by Django 5.0.7 on 2024-08-20 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0022_siteinventoryfolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryhistory',
            name='site_inventory_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='po.siteinventoryfolder'),
        ),
    ]
