# Generated by Django 5.0.7 on 2024-08-20 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0023_inventoryhistory_site_inventory_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminventory',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='po.siteinventoryfolder'),
        ),
    ]
