# Generated by Django 5.0.7 on 2024-08-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0024_iteminventory_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryhistory',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
