# Generated by Django 5.0.7 on 2024-08-21 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0025_alter_inventoryhistory_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInventoryFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='iteminventory',
            name='folder',
        ),
        migrations.AddField(
            model_name='inventoryhistory',
            name='client',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='iteminventory',
            name='client',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='iteminventory',
            name='site_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_item_inventories', to='po.siteinventoryfolder'),
        ),
        migrations.AddField(
            model_name='iteminventory',
            name='site_or_client_choice',
            field=models.CharField(choices=[('site', 'Site Delivered'), ('client', 'Client')], default='site', max_length=10),
        ),
        migrations.AddField(
            model_name='inventoryhistory',
            name='client_inventory_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='po.clientinventoryfolder'),
        ),
        migrations.AddField(
            model_name='iteminventory',
            name='client_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_item_inventories', to='po.clientinventoryfolder'),
        ),
    ]
