# Generated by Django 5.0.7 on 2024-08-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0026_clientinventoryfolder_remove_iteminventory_folder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminventory',
            name='site_or_client_choice',
            field=models.CharField(blank=True, choices=[('site', 'Site Delivered'), ('client', 'Client')], max_length=10, null=True),
        ),
    ]
