# Generated by Django 5.0.7 on 2024-08-21 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0027_alter_iteminventory_site_or_client_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteminventory',
            name='client_folder',
        ),
        migrations.RemoveField(
            model_name='iteminventory',
            name='site_folder',
        ),
        migrations.AddField(
            model_name='iteminventory',
            name='client_inventory_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='po.clientinventoryfolder'),
        ),
        migrations.AddField(
            model_name='iteminventory',
            name='site_inventory_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='po.siteinventoryfolder'),
        ),
    ]
