# Generated by Django 5.0.7 on 2024-08-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0028_remove_iteminventory_client_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryhistory',
            name='delivery_no',
            field=models.CharField(max_length=255, null=True, verbose_name='Delivery No.'),
        ),
        migrations.AddField(
            model_name='inventoryhistory',
            name='delivery_ref',
            field=models.CharField(choices=[('PL', 'PL'), ('DR', 'DR'), ('TR', 'TR')], max_length=2, null=True, verbose_name='Delivery Ref#'),
        ),
        migrations.AddField(
            model_name='inventoryhistory',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Invoice No.'),
        ),
        migrations.AddField(
            model_name='inventoryhistory',
            name='invoice_type',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('Invoice', 'Invoice'), ('CI', 'CI')], max_length=10, null=True, verbose_name='Invoice#'),
        ),
        migrations.AddField(
            model_name='iteminventory',
            name='delivery_no',
            field=models.CharField(max_length=255, null=True, verbose_name='Delivery No.'),
        ),
        migrations.AddField(
            model_name='iteminventory',
            name='delivery_ref',
            field=models.CharField(choices=[('PL', 'PL'), ('DR', 'DR'), ('TR', 'TR')], max_length=2, null=True, verbose_name='Delivery Ref#'),
        ),
        migrations.AddField(
            model_name='iteminventory',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Invoice No.'),
        ),
        migrations.AddField(
            model_name='iteminventory',
            name='invoice_type',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('Invoice', 'Invoice'), ('CI', 'CI')], max_length=10, null=True, verbose_name='Invoice#'),
        ),
    ]
