# Generated by Django 5.0.7 on 2024-08-24 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0029_inventoryhistory_delivery_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='item_code',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='particulars',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='price',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='unit',
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Item Code')),
                ('particulars', models.CharField(max_length=255, null=True, verbose_name='Particulars')),
                ('quantity', models.IntegerField(null=True, verbose_name='Quantity')),
                ('unit', models.CharField(blank=True, max_length=255, null=True, verbose_name='Unit')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Price')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Total Amount')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='po.purchaseorder')),
            ],
        ),
    ]
