# Generated by Django 5.0.7 on 2024-08-24 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0030_remove_purchaseorder_item_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='item_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Item Code'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='particulars',
            field=models.CharField(max_length=255, null=True, verbose_name='Particulars'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Total Amount'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Unit'),
        ),
        migrations.DeleteModel(
            name='PurchaseOrderItem',
        ),
    ]
