# Generated by Django 5.0.7 on 2024-08-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0031_purchaseorder_item_code_purchaseorder_particulars_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkInventoryUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('new_product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity_in', models.IntegerField()),
                ('quantity_out', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('site_or_client_choice', models.CharField(blank=True, choices=[('site', 'Site Delivered'), ('client', 'Client')], max_length=10, null=True)),
                ('site_delivered', models.CharField(blank=True, max_length=255, null=True, verbose_name='Site Delivered')),
                ('client', models.CharField(blank=True, max_length=255, null=True, verbose_name='Client')),
                ('delivery_ref', models.CharField(choices=[('PL', 'PL'), ('DR', 'DR'), ('TR', 'TR')], max_length=2, null=True, verbose_name='Delivery Ref#')),
                ('delivery_no', models.CharField(max_length=255, null=True, verbose_name='Delivery No.')),
                ('invoice_type', models.CharField(blank=True, choices=[('SI', 'SI'), ('Invoice', 'Invoice'), ('CI', 'CI')], max_length=10, null=True, verbose_name='Invoice#')),
                ('invoice_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Invoice No.')),
            ],
        ),
    ]
