# Generated by Django 5.0.7 on 2024-08-25 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0032_bulkinventoryupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BulkInventoryUpdate',
        ),
    ]
