# Generated by Django 5.0.7 on 2024-08-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0034_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminventory',
            name='delivery_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Delivery No.'),
        ),
        migrations.AlterField(
            model_name='iteminventory',
            name='delivery_ref',
            field=models.CharField(blank=True, choices=[('PL', 'PL'), ('DR', 'DR'), ('TR', 'TR')], max_length=2, null=True, verbose_name='Delivery Ref#'),
        ),
    ]
