# Generated by Django 5.0.7 on 2024-08-28 08:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0035_alter_iteminventory_delivery_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminventory',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
