# Generated by Django 5.0.7 on 2024-08-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0036_iteminventory_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryhistory',
            name='site_or_client_choice',
            field=models.CharField(blank=True, choices=[('site', 'Site Delivered'), ('client', 'Client')], max_length=10, null=True),
        ),
    ]
