# Generated by Django 5.0.7 on 2024-08-29 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0037_inventoryhistory_site_or_client_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='poCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fbbd_ref_number', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks2', models.CharField(blank=True, max_length=100, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='po.purchaseorder')),
            ],
        ),
    ]
