# Generated by Django 5.0.7 on 2024-08-29 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0038_pocart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pocart',
            old_name='item',
            new_name='particulars',
        ),
    ]
