# Generated by Django 5.0.7 on 2024-08-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0039_rename_item_pocart_particulars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='remarks2',
            field=models.CharField(blank=True, choices=[('On Hold', 'On Hold'), ('For Signature', 'For Signature'), ('Cancelled', 'Cancelled'), ('Paid', 'Paid')], max_length=20, null=True, verbose_name='Remarks2'),
        ),
    ]
