# Generated by Django 5.0.7 on 2024-08-30 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0040_alter_purchaseorder_remarks2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Delivery No.'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_ref',
            field=models.CharField(blank=True, choices=[('PL', 'PL'), ('DR', 'DR'), ('TR', 'TR')], max_length=2, null=True, verbose_name='Delivery Ref#'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='particulars',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Particulars'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PO#'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchaser',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Purchaser'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Amount'),
        ),
    ]
