# Generated by Django 5.0.7 on 2024-08-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0041_alter_purchaseorder_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pocart',
            name='remarks2',
            field=models.CharField(blank=True, choices=[('On Hold', 'On Hold'), ('For Signature', 'For Signature'), ('Cancelled', 'Cancelled'), ('Paid', 'Paid')], max_length=20, null=True, verbose_name='Remarks2'),
        ),
    ]
