# Generated by Django 5.0.7 on 2024-09-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0042_alter_pocart_remarks2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCodeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100)),
                ('po_product_name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
    ]
