# Generated by Django 5.0.7 on 2024-09-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0043_itemcodelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminventory',
            name='quantity_in',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='iteminventory',
            name='quantity_out',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='iteminventory',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
