# Generated by Django 5.0.7 on 2024-09-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0044_alter_iteminventory_quantity_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteminventory',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='iteminventory',
            name='quantity_in',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='iteminventory',
            name='quantity_out',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='iteminventory',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
