# Generated by Django 5.0.7 on 2024-09-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0045_remove_iteminventory_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminventory',
            name='invoice_type',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('TR', 'TR'), ('CI', 'CI')], max_length=10, null=True, verbose_name='Invoice#'),
        ),
    ]
