# Generated by Django 5.0.7 on 2024-09-07 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0046_alter_iteminventory_invoice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryhistory',
            name='quantity_in',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryhistory',
            name='quantity_out',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryhistory',
            name='stock',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='iteminventory',
            name='quantity_in',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='iteminventory',
            name='quantity_out',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='iteminventory',
            name='stock',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='StockInHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('po_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='PO#')),
                ('purchaser', models.CharField(blank=True, max_length=255, null=True, verbose_name='Purchaser')),
                ('item_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Item Code')),
                ('particulars', models.CharField(blank=True, max_length=255, null=True, verbose_name='Particulars')),
                ('quantity_in', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=255, null=True, verbose_name='Unit')),
                ('fbbd_ref_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='FBBD Ref#')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('supplier', models.CharField(blank=True, max_length=255, null=True, verbose_name='Supplier')),
                ('delivery_ref', models.CharField(blank=True, choices=[('PL', 'PL'), ('DR', 'DR'), ('TR', 'TR')], max_length=2, null=True, verbose_name='Delivery Ref#')),
                ('delivery_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Delivery No.')),
                ('invoice_type', models.CharField(blank=True, choices=[('SI', 'SI'), ('Invoice', 'Invoice'), ('CI', 'CI')], max_length=10, null=True, verbose_name='Invoice#')),
                ('invoice_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Invoice No.')),
                ('payment_req_ref', models.CharField(blank=True, max_length=255, null=True, verbose_name='Payment Req Ref#')),
                ('payment_details', models.TextField(blank=True, choices=[('Check Voucher', 'Check Voucher'), ('Cash Voucher', 'Cash Voucher')], max_length=20, null=True, verbose_name='Payment Details')),
                ('remarks2', models.CharField(blank=True, choices=[('On Hold', 'On Hold'), ('For Signature', 'For Signature'), ('Cancelled', 'Cancelled'), ('Paid', 'Paid')], max_length=20, null=True, verbose_name='Remarks2')),
                ('supplier_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='po.supplierfolder')),
            ],
        ),
    ]
