# Generated by Django 5.0.7 on 2024-09-08 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0047_alter_inventoryhistory_quantity_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
